---
apiVersion: v1
kind: ConfigMap
metadata:
  name: urlaubsverwaltung-database-dump
  namespace: urlaubsverwaltung
data:
  db: urlaubsverwaltung
  dbhost: xxx
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: urlaubsverwaltung-database-dump
  namespace: urlaubsverwaltung
spec:
  schedule: '48 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: mysqldump-docker-registry
          containers:
            - name: urlaubsverwaltung-database-dump
              image: synyx/mysqldump-docker:0.8 # will be available soon
              env:
                - name: DB_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: urlaubsverwaltung-database-dump
                      key: db
                - name: DB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: urlaubsverwaltung-database-dump
                      key: dbhost
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: urlaubsverwaltung-mariadb
                      key: databaseUser
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: urlaubsverwaltung-mariadb
                      key: databasePassword
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              volumeMounts:
                - mountPath: /mysqldump
                  name: urlaubsverwaltung-database-dump
          volumes:
            - name: urlaubsverwaltung-database-dump
              glusterfs:
                endpoints: gluster
                path: kubernetes-backup
          restartPolicy: OnFailure
